version: "3.1"
services:

  db-government:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: government
    ports:
      - 5433:5432

  government:
    image: redxice/government:deploy
    ports:
      - 9070:8080
      - 4849:4848
      - 8182:8181

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracking
    ports:
      - 5432:5432
  tracking:
    image: redxice/payara:jenkins
    ports:
      - 9050:8080
      - 4848:4848
      - 8181:8181
